### ISSUE TITLE
Do not display icons in Android version 5.1.1

### ISSUE THREAD

**Issue by mmfarzaneh** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#16]
Hi dear 
In Android 6 and above, it shows icons without any problem, but in Android 5, it does not show. Can you help me?
Thank you

**Comment by MahdiFarzami** [comment]
i have same probleam.

**Comment by shwetachauhan-simform** [comment]
@mmfarzaneh , @MahdiFarzami : I have checked in 5.1.1 emulator and it's working. Can you please share more detail??

**Comment by ShwetaChauhan18** [comment]
not able to reproduce
