### ISSUE TITLE
Do not display icon on android below 7

### ISSUE THREAD

**Issue by MahdiFarzami** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#17]
i have probleam on display icon on android 6. icon display on android 7 and above but on android 6 i get this error : android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/ic_home.png

**Comment by shwetachauhan-simform** [comment]
Ok, I will check ASAP

**Comment by abhishek-1-simform** [comment]
@MahdiFarzami  Can you please try to add that ic_home.png image to your drawable(only drawable not -xhdpi-v4) folder. And if it still not work let us know.

**Comment by MahdiFarzami** [comment]
> @MahdiFarzami Can you please try to add that ic_home.png image to your drawable(only drawable not -xhdpi-v4) folder. And if it still not work let us know.

i add file to drawable folder and get same error

**Comment by shwetachauhan-simform** [comment]
Ok, I will check tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shwetachauhan-simform** [comment]
@MahdiFarzami : I have checked in almost all OS device and It's working. Can you please share more detail??

**Comment by MahdiFarzami** [comment]
in your example you use svg/xml file for icon, if you try with png file it not display at android below 7

**Comment by ShwetaChauhan18** [comment]
Not able to reproduce
