### ISSUE TITLE
how do setup with navcontroller?

### ISSUE THREAD

**Issue by Suret1** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#22]
For example, I click the text in A fragment and switch to B fragment, but bottomnavigation menu does not change, Is there any solution to do this?

**Comment by ShwetaChauhan18** [comment]
@Suret1 : I will check feasibility for that and update you ASAP. Thanks for this

**Comment by RuchaBhattJoshi** [comment]
I guess I have the same question how to use with navController?

**Comment by ShwetaChauhan18** [comment]
I am working on this, I will update you soon

**Comment by RuchaBhattJoshi** [comment]
Thank you, Shweta :)

**Comment by ShwetaChauhan18** [comment]
@RuchaBhattJoshi @Suret1 : I will complete this tomorrow and release new version

**Comment by Suret1** [comment]
> @RuchaBhattJoshi @Suret1 : I will complete this tomorrow and release new version

ThanX Shweta. 😊

**Comment by RuchaBhattJoshi** [comment]
thank you @ShwetaChauhan18, I'll integrate it. :)

**Comment by ShwetaChauhan18** [comment]
@RuchaBhattJoshi @Suret1 : Library updated with Jetpack Navigation support.

**Comment by Suret1** [comment]
> @RuchaBhattJoshi @Suret1 : Library updated with Jetpack Navigation support.

ThanX @ShwetaChauhan18 ! I will integrate it into my project

**Comment by ShwetaChauhan18** [comment]
sure, let me know for any issue and give us star if it helps
