### ISSUE TITLE
How to remove the wave from an active link?

### ISSUE THREAD

**Issue by vlaidet** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#31]
Hello everyone,
I'm trying to do the reverse of the SSCustomBottomNavigation.show(int id, boolean enableAnimation) method.

I want to remove the wave when I click on another element on my page.

Do you have any ideas? Is there a method to do this?

**Comment by shwetachauhan-simform** [comment]
@KeyToxx : We will check and get back to you ASAP

**Comment by KeyToxx** [comment]
@shwetachauhan-simform Thank you !

**Comment by KeyToxx** [comment]
Hi @shwetachauhan-simform
Were you able to find a solution ?

**Comment by MehulKK** [comment]
@vlaidet  : you mean down curve for selected item?

**Comment by vlaidet** [comment]
@MehulKK Yes that's right

**Comment by MehulKK** [comment]
@vlaidet  : This is a new enhancement. Will work in this in future.

**Comment by MehulKK** [comment]
@vlaidet  : I have added feature and release new version you can check updated readme.md file

**Comment by MehulKK** [comment]
@vlaidet  : Njoy new feature :)
