### ISSUE TITLE
Android 6: Icon not showing up

### ISSUE THREAD

**Issue by karagarwal** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#41]
Bottom Nav Icon are not showing when app is installed in ANDROID 6 Devices.
 Tried with SVG and PNG icons

**Comment by ShwetaChauhan18** [comment]
@karagarwal : Is it working?? Issue resolved?

**Comment by karagarwal** [comment]
@ShwetaChauhan18 
 if icon has alpha, then it is creating issue
   So for workaround removed alpha from my icons, and working up perfectly
