### ISSUE TITLE
Found a phenomenon, maybe a bug

### ISSUE THREAD

**Issue by SmallRedSister** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#43]
https://user-images.githubusercontent.com/29477112/193274980-b06dc854-49c6-422c-b9bc-3060ba06b8fe.mp4

Huawei mobile phone test only adds the EditView control to the fragment. The ED loses focus and cannot input content.

**Comment by AshvinVavaliya** [comment]
Hi [SmallRedSister](https://github.com/SmallRedSister)
Sorry for late, We are finding proper solution for this issue and update you ASAP.

**Comment by AshvinVavaliya** [comment]
Hello [SmallRedSister](https://github.com/SmallRedSister)
Your issue is fixed, try it out with latest version and let me know.
