### ISSUE TITLE
ICONS remains activated when other icon selected

### ISSUE THREAD

**Issue by karagarwal** [SimformSolutionsPvtLtd/SSCustomBottomNavigation#44]
If we switched between menu too quickly then strange phenomena is observed,
 I am attaching Screen Recording for reference

Note: This this is observed while performing Negative Testing.
Please help with some kind of workaround for same

https://user-images.githubusercontent.com/23401081/195522482-f4760a08-1f97-4b92-9f9b-94c2e198a14a.mp4

**Comment by AshvinVavaliya** [comment]
Hi [karagarwal](https://github.com/karagarwal),
Sorry for late, We are finding proper solution for this issue and update you ASAP.

**Comment by AshvinVavaliya** [comment]
Hello [karagarwal](https://github.com/karagarwal)
Your issue is fixed, try it out with latest version and let me know.

**Comment by karagarwal** [comment]
Hello @AshvinVavaliya 
Thanks for the reply the issue was fixed in 3.5, but recent changes now it leads to one major bug
Details:
File :  custombottomnavigation/src/main/java/com/simform/custombottomnavigation/SSCustomBottomNavigation.kt
line 222 & 226
//Current Code
   if (TextUtils.isEmpty(iconTextTypeFace))    //Line 222
   if (TextUtils.isEmpty(typeface))                 //line 226
//What should be
    if (!iconTextTypeFace.isNullOrBlank())        //line 222
     if (!typeface.isNullOrBlank())                     //line 226
    
   **What Causing Bug:**
    If typeface attributes are not used in XML Component then it will lead to crash
    
   **How Bug Arsie** 
    in Update v3.5  the conditions got reversed from null_empty to empty

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/23401081/235449512-a8f414b8-76c4-4866-a193-7f4085bba36a.png)
